In [1]:
# ============================================================
# Information Extraction (IE) from
# Structured / Unstructured Documents
# ============================================================

# Step 1: Install Required Libraries
!pip install pandas spacy openpyxl

# Download English NLP Model
!python -m spacy download en_core_web_sm


# Step 2: Import Libraries
import pandas as pd
import spacy
import re
from IPython.display import display


# Step 3: Load spaCy Model
nlp = spacy.load("en_core_web_sm")


# ============================================================
# PART A: INFORMATION EXTRACTION FROM UNSTRUCTURED TEXT
# ============================================================

# Step 4: Create Unstructured Document
text = """
John Smith is working at Google India as a Software Engineer.
He is located in Bangalore, India.

His email address is john.smith@gmail.com and his phone number
is +91-9876543210.

John has experience in Python, Java, Machine Learning,
Data Science and SQL.

He joined Google on 15 January 2024.
The project deadline is 30 September 2026.
"""


print("========== ORIGINAL DOCUMENT ==========\n")
print(text)


# Step 5: Process Text using spaCy
doc = nlp(text)


# Step 6: Named Entity Recognition (NER)
print("\n========== NAMED ENTITIES ==========\n")

entities = []

for ent in doc.ents:
    entities.append({
        "Entity": ent.text,
        "Label": ent.label_,
        "Description": spacy.explain(ent.label_)
    })

entity_df = pd.DataFrame(entities)

display(entity_df)


# Step 7: Extract Person Names
persons = [
    ent.text
    for ent in doc.ents
    if ent.label_ == "PERSON"
]

print("\n========== PERSON ==========")
print(persons)


# Step 8: Extract Organizations
organizations = [
    ent.text
    for ent in doc.ents
    if ent.label_ == "ORG"
]

print("\n========== ORGANIZATION ==========")
print(organizations)


# Step 9: Extract Locations
locations = [
    ent.text
    for ent in doc.ents
    if ent.label_ in ["GPE", "LOC"]
]

print("\n========== LOCATION ==========")
print(locations)


# Step 10: Extract Dates
dates = [
    ent.text
    for ent in doc.ents
    if ent.label_ == "DATE"
]

print("\n========== DATES ==========")
print(dates)


# ============================================================
# PART B: REGULAR EXPRESSION BASED INFORMATION EXTRACTION
# ============================================================

# Step 11: Extract Email Address
emails = re.findall(
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
    text
)

print("\n========== EMAIL ==========")
print(emails)


# Step 12: Extract Phone Number
phones = re.findall(
    r'(?:\+91[-\s]?)?[6-9]\d{9}',
    text
)

print("\n========== PHONE NUMBER ==========")
print(phones)


# Step 13: Extract Skills
skills_list = [
    "Python",
    "Java",
    "Machine Learning",
    "Data Science",
    "SQL",
    "C++",
    "JavaScript",
    "HTML",
    "CSS",
    "Deep Learning"
]

found_skills = []

for skill in skills_list:
    if re.search(
        r'\b' + re.escape(skill) + r'\b',
        text,
        re.IGNORECASE
    ):
        found_skills.append(skill)

print("\n========== SKILLS ==========")
print(found_skills)


# ============================================================
# PART C: CREATE FINAL EXTRACTED INFORMATION TABLE
# ============================================================

# Step 14: Combine Extracted Information

person_name = persons[0] if persons else None
organization = organizations[0] if organizations else None
location = locations[0] if locations else None

extracted_information = {
    "Name": person_name,
    "Organization": organization,
    "Location": location,
    "Email": emails[0] if emails else None,
    "Phone": phones[0] if phones else None,
    "Dates": ", ".join(dates),
    "Skills": ", ".join(found_skills)
}

final_df = pd.DataFrame([extracted_information])


print("\n========== EXTRACTED INFORMATION ==========\n")

display(final_df)


# ============================================================
# PART D: INFORMATION EXTRACTION FROM STRUCTURED DATA
# ============================================================

# Step 15: Create Structured Dataset

structured_data = {
    "Name": [
        "Rahul",
        "Priya",
        "Aman",
        "Neha"
    ],

    "Email": [
        "rahul@gmail.com",
        "priya@gmail.com",
        "aman@gmail.com",
        "neha@gmail.com"
    ],

    "Department": [
        "CSE",
        "AI",
        "IT",
        "CSE"
    ],

    "Skills": [
        "Python, SQL",
        "Machine Learning, Python",
        "Java, SQL",
        "Python, Java"
    ]
}

structured_df = pd.DataFrame(structured_data)


print("\n========== STRUCTURED DATA ==========\n")

display(structured_df)


# Step 16: Extract Specific Information
print("\n========== CSE STUDENTS ==========\n")

cse_students = structured_df[
    structured_df["Department"] == "CSE"
]

display(cse_students)


# ============================================================
# PART E: EXTRACT INFORMATION FROM CSV FILE
# ============================================================

# Step 17: Save Structured Data as CSV

structured_df.to_csv(
    "student_information.csv",
    index=False
)

print("\nCSV file created successfully!")


# Step 18: Read CSV File

loaded_df = pd.read_csv(
    "student_information.csv"
)

print("\n========== DATA LOADED FROM CSV ==========\n")

display(loaded_df)


# ============================================================
# PART F: SEARCH INFORMATION FROM DOCUMENT
# ============================================================

# Step 19: Search for Specific Information

search_words = [
    "Python",
    "Google",
    "Machine Learning",
    "Bangalore"
]

print("\n========== SEARCH RESULTS ==========\n")

for word in search_words:

    if word.lower() in text.lower():
        print(f"{word}: Found")
    else:
        print(f"{word}: Not Found")


# ============================================================
# PART G: FINAL SUMMARY
# ============================================================

print("\n==============================================")
print("        INFORMATION EXTRACTION SUMMARY")
print("==============================================")

print("Name:", person_name)
print("Organization:", organization)
print("Location:", location)
print("Email:", emails)
print("Phone:", phones)
print("Dates:", dates)
print("Skills:", found_skills)

print("\nInformation Extraction Completed Successfully!")

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: spacy in /usr/local/lib/python3.13/dist-packages (3.8.16)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (0.27.2)
Requirement already satisfied: click<9.0.0,>=8.2.1 in /usr/local/lib/python3.13/dist-packages (from spacy) (8.5.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (2.13.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from spacy) (80.10.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from spacy) (26.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.46.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.7.22)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.5)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.15.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.21.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.4.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 89.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.
========== ORIGINAL DOCUMENT ==========


John Smith is working at Google India as a Software Engineer.
He is located in Bangalore, India.

His email address is john.smith@gmail.com and his phone number
is +91-9876543210.

John has experience in Python, Java, Machine Learning,
Data Science and SQL.

He joined Google on 15 January 2024.
The project deadline is 30 September 2026.


========== NAMED ENTITIES ==========

,Entity,Label,Description
0,John Smith,PERSON,"People, including fictional"
1,Google India,LOC,"Non-GPE locations, mountain ranges, bodies of ..."
2,Bangalore,GPE,"Countries, cities, states"
3,India,GPE,"Countries, cities, states"
4,John,PERSON,"People, including fictional"
5,Python,GPE,"Countries, cities, states"
6,Java,PERSON,"People, including fictional"
7,Machine Learning,PERSON,"People, including fictional"
8,Data Science,ORG,"Companies, agencies, institutions, etc."
9,SQL,ORG,"Companies, agencies, institutions, etc."
10,Google,ORG,"Companies, agencies, institutions, etc."
11,15 January 2024,DATE,Absolute or relative dates or periods
12,30 September 2026,DATE,Absolute or relative dates or periods

========== PERSON ==========
['John Smith', 'John', 'Java', 'Machine Learning']

========== ORGANIZATION ==========
['Data Science', 'SQL', 'Google']

========== LOCATION ==========
['Google India', 'Bangalore', 'India', 'Python']

========== DATES ==========
['15 January 2024', '30 September 2026']

========== EMAIL ==========
['john.smith@gmail.com']

========== PHONE NUMBER ==========
['+91-9876543210']

========== SKILLS ==========
['Python', 'Java', 'Machine Learning', 'Data Science', 'SQL']

========== EXTRACTED INFORMATION ==========

,Name,Organization,Location,Email,Phone,Dates,Skills
0,John Smith,Data Science,Google India,john.smith@gmail.com,+91-9876543210,"15 January 2024, 30 September 2026","Python, Java, Machine Learning, Data Science, SQL"

========== STRUCTURED DATA ==========

    Name            Email Department                    Skills
0  Rahul  rahul@gmail.com        CSE               Python, SQL
1  Priya  priya@gmail.com         AI  Machine Learning, Python
2   Aman   aman@gmail.com         IT                 Java, SQL
3   Neha   neha@gmail.com        CSE              Python, Java

========== CSE STUDENTS ==========

    Name            Email Department        Skills
0  Rahul  rahul@gmail.com        CSE   Python, SQL
3   Neha   neha@gmail.com        CSE  Python, Java

CSV file created successfully!

========== DATA LOADED FROM CSV ==========

    Name            Email Department                    Skills
0  Rahul  rahul@gmail.com        CSE               Python, SQL
1  Priya  priya@gmail.com         AI  Machine Learning, Python
2   Aman   aman@gmail.com         IT                 Java, SQL
3   Neha   neha@gmail.com        CSE              Python, Java

========== SEARCH RESULTS ==========

Python: Found
Google: Found
Machine Learning: Found
Bangalore: Found

==============================================
        INFORMATION EXTRACTION SUMMARY
==============================================
Name: John Smith
Organization: Data Science
Location: Google India
Email: ['john.smith@gmail.com']
Phone: ['+91-9876543210']
Dates: ['15 January 2024', '30 September 2026']
Skills: ['Python', 'Java', 'Machine Learning', 'Data Science', 'SQL']

Information Extraction Completed Successfully!